# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.4'

- script: |
    npm install
    npm start &
  displayName: 'npm install'

- script: |
    gem install selenium-webdriver
    ruby testScripts/automate_test.rb
  env:
    BROWSERSTACK_USERNAME: $(BROWSERSTACK_USERNAME)
    BROWSERSTACK_ACCESS_KEY: $(BROWSERSTACK_ACCESS_KEY)
  displayName: 'Run Bstack test'
  
  - task: BrowserStackResults@0

